---

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'jnicrimi'
    reviewers:
      - 'jnicrimi'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'jnicrimi'
    reviewers:
      - 'jnicrimi'
